lane :test do
  token = ''
  app_id = ''
  farol(token: token, app_id: app_id)
end

lane :local_api_version do
  ENV["FAROL_URL"] = 'http://localhost:3000'
  token = ''
  verb = 'get'
  method = 'version'
  puts farol_api(token: token, verb: verb, method: method)
end

lane :remote_api_version do
  token = ''
  verb = 'get'
  method = 'version'
  puts farol_api(token: token, verb: verb, method: method)
end

lane :version do
  token = ''
  platform = 'ios'

  result = farol_get_version(token: token, platform: platform)
  puts result

  farol_set_version(token: token, platform: platform, version: '1.0.0', build: 0)

  result = farol_get_version(token: token, platform: platform)
  puts result
end
